version: '3.8'

services:
  # Neon Local proxy for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432', '-U', 'neon']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - acquisitions-dev

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reloading in development
      - ./src:/app/src:ro
      # Mount only the package.json (do NOT mount the whole /app directory or use a glob)
      - ./package.json:/app/package.json:ro
      # If you use a package-lock.json you can also mount it explicitly (uncomment the line below)
      # - ./package-lock.json:/app/package-lock.json:ro
      - ./drizzle.config.js:/app/drizzle.config.js:ro
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-dev
    restart: unless-stopped

networks:
  acquisitions-dev:
    driver: bridge
