name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier check
        id: prettier
        run: npm run format:check
        continue-on-error: true

      - name: Add annotations and fail if issues found
        if: steps.eslint.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: |
          if [ "${{ steps.eslint.outcome }}" = "failure" ]; then
            echo "::error::ESLint found issues. To try auto-fixing locally, run: npm run lint:fix"
          fi
          if [ "${{ steps.prettier.outcome }}" = "failure" ]; then
            echo "::error::Prettier check failed. To format files locally, run: npm run format"
          fi

          {
            echo "## Lint and format results"
            if [ "${{ steps.eslint.outcome }}" = "failure" ]; then
              echo "- ESLint: failed. Suggestion: run \`npm run lint:fix\` locally."
            else
              echo "- ESLint: passed."
            fi
            if [ "${{ steps.prettier.outcome }}" = "failure" ]; then
              echo "- Prettier: failed. Suggestion: run \`npm run format\` locally."
            else
              echo "- Prettier: passed."
            fi
          } >> "$GITHUB_STEP_SUMMARY"

          exit 1
