name: Tests

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NODE_OPTIONS: --experimental-vm-modules
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: run-tests
        run: |
          if npm run -s | grep -q "^  test"; then
            npm test -- --coverage
          else
            echo "::warning::No test script found in package.json. Skipping tests."
            echo "### Tests skipped" >> "$GITHUB_STEP_SUMMARY"
            echo "No test script defined in package.json. Configure tests to enable CI test runs." >> "$GITHUB_STEP_SUMMARY"
            exit 0
          fi
        continue-on-error: true

      - name: Upload coverage artifact
        if: steps.run-tests.outcome == 'success' || steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/**
            coverage.*.json
            **/coverage/lcov.info
          if-no-files-found: ignore
          retention-days: 30

      - name: Summary (success)
        if: steps.run-tests.outcome == 'success'
        run: |
          echo "### Test results" >> "$GITHUB_STEP_SUMMARY"
          if [ -f coverage/lcov.info ]; then
            lines=$(grep -c '^DA:' coverage/lcov.info || true)
            echo "- Coverage file found. Lines recorded: $lines" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- Coverage file not found. See job logs for details." >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Annotate failures and fail
        if: steps.run-tests.outcome == 'failure'
        run: |
          echo "::error::Tests failed. See logs above. Re-run locally with: npm test"
          echo "### Test results" >> "$GITHUB_STEP_SUMMARY"
          echo "- Tests failed. Check the job logs and error output." >> "$GITHUB_STEP_SUMMARY"
          exit 1
